services:
  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
        ./public:/usr/share/nginx/html  # mount โฟลเดอร์ Public ที่มี html
    depends_on:
      - express
    networks:
      - my-network

  express:
    build:
      context: ./express  # เส้นทางที่มี Dockerfile
    container_name: express-container
    ports:
      - "3001:3000"
    depends_on:
      - mongodb
    environment: 
      - MONGODB_URI=mongodb://mongodb-container:27017/your_database_name  # เชื่อมต่อกับ MongoDB
    volumes:
      - ./express:/usr/src/app  # mount โฟลเดอร์โปรเจ็กต์ไปที่ Host machine
    networks:
      - my-network

  mongodb:
    image: mongo:4.4
    container_name: mongodb-container
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db  # mount volume ไปที่ Host machine
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

